# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f3681683237d6406c83c290eb6532cbae8391575c6cf198a08e08ec94114f1380cb1dd0ca5bea114193946278dec1c80a47c2f0416c275e5ae45e5fe1a0735c

test:
  secret_key_base: 174559148cbc40c8b2e2fe211c21644428a987424f2a880e8aa198c32fd115fa415c138e78007c7052121982772cfd1681ca2e38b95d896e486dbc8c73cc6484

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
